### ISSUE TITLE
03.25.2024 28장, 33장, 34장

### ISSUE THREAD

**Issue by ooheunda** [ooheunda/js-deep-dive#12]
12회차 퀴즈 담당
세민, 재연, 하온

```
<details>
<summary>정답 보기</summary>
<div>

여기에 정답을 써주세요

</div>
</details>
```

**Comment by HA0N1** [comment]
```javascript
const num = Number("123.456");

console.log(num.toFixed(2));   // ??
console.log(num.toPrecision(4)); //  ??
console.log(num === 123.456);  // ??
```

<details>
<summary>정답 보기</summary>
<div>

1) "123.46" 인수만큼 소수자리 반올림 후 문자열 반환
2) "123.5" 인수만큼 전체 자리수 반올림 후 문자열 반환
3) true

</div>
</details>

```javascript
const symbol1 = Symbol();
const symbol2 = Symbol();
const symbol3 = Symbol('hi');

console.log(symbol1); // ??
console.log(symbol2); // ??
console.log(symbol3); // ??
console.log(symbol1 === symbol2); // ??
console.log(symbol3 === Symbol('hi')); // ??
```

<details>
<summary>정답 보기</summary>
<div>

1)  Symbol()
2) Symbol()
3) Symbol('hi')
4) false
5) false   심볼은 고유값을 가짐. 문자열로 동등비교해도 무적권 false. 키를 비교하는게 맞음

</div>
</details>


이터레이션 프로토콜에 따라, 이터러블 객체가 가져야 하는 메서드 
1. iterate() 
2. getIterator() 
3. Symbol.iterator() 
4. next()




<details>
<summary>정답 보기</summary>
<div>

3. Symbol.iterator() 

</div>
</details>

**Comment by APD-Kim** [comment]
1. Number.EPSILON을 사용하는 이유
<details>
<summary>정답 보기</summary>
<div>

IEEE 754에서 2진법으로 변환했을 때 무한소수가 되어 발생하는 부동소수점으로 인한 미세한 오차를 해결하기 위해 사용함.

</div>
</details>


2. 아래에 있는 두개의 코드의 차이점은 무엇인가?
```js
const s1 = Symbol.for("bird");
console.log(Symbol.keyFor(s1));

const s2 = Symbol("eagle");
console.log(Symbol.keyFor(s2));
```
<details>
<summary>정답 보기</summary>
<div>

Symbol.for을 사용하면 bird값이 전역 심벌 레지스트리에 저장됨. 
정확히는 bird라는 키롤 저장된 심벌 값이 없다면 저장됨
그냥 Symbol만으로 값을 정의한다면 전역 심벌 레지스트리에 등록되지 않음.

</div>
</details>


3. 지연평가의 장점은 무엇인가?
<details>
<summary>정답 보기</summary>
<div>

지연 평가를 사용하면 불필요한 데이터를 미리 생성하지 않고, 필요한 데이터를 필요한 순간에 생성한다.
불필요한 메모리 소비 x, 실행 속도가 빠름, 미리 생성하지 않기 때문에 무한을 표현할 수 있음

</div>
</details>
