### ISSUE TITLE
03.30.2024 29장, 30장, 35장, 36장

### ISSUE THREAD

**Issue by ooheunda** [ooheunda/js-deep-dive#13]
13회차 퀴즈 담당
세민, 재연, 다은

```
<details>
<summary>정답 보기</summary>
<div>

여기에 정답을 써주세요

</div>
</details>
```

**Comment by ooheunda** [comment]
1. 
```javascript
let arr1 = [1, 2, 3];
let arr2 = [4, 5, 6];

// (1) arr1, arr2를 사용해 새로운 배열 arr3 = [1, 2, 3, 4, 5, 6]을 만들어보기

// (2) arr1, arr2와 splice 메서드 사용해 새로운 배열 arr4 = [1, 2, 4, 5, 6] 만들어보기

```

<details>
<summary>정답 보기</summary>
<div>

```javascript
// (1) arr1, arr2를 사용해 새로운 배열 arr3 = [1, 2, 3, 4, 5, 6]을 만들어보기
let arr3 = [...arr1, ...arr2];

// (2) arr1, arr2와 splice 메서드를 사용해 새로운 배열 arr4 = [1, 2, 4, 5, 6] 만들어보기
arr1.splice(2, 1, ...arr2);
let arr4 = [...arr1];
```

</div>
</details>

<hr>

2. 배열과 객체의 구조 분해 할당 기준은?

<details>
<summary>정답 보기</summary>
<div>

배열은 인덱스(순서)
객체는 프로퍼티 키

</div>
</details>

<hr>

3.
```javascript
let num1 = -1.3423;
let num2 = -1;

console.log(Math.max(num1, num2)); // (1)
console.log(Math.floor(num1)); // (2)
console.log(Math.abs(num2)); // (3)
```

<details>
<summary>정답 보기</summary>
<div>

1. -1
2. -2
3. 1

</div>
</details>

**Comment by bubblegum95** [comment]
#### 문제1. 스프레드 문법의 결과는 ㄱ.이/가 아니다. 따라서 스프레드 문법의 결과는 ㄴ.에 할당할 수 없다.

<details>
<summary>정답 보기</summary>
<div>

정답: 값, 변수

</div>
</details>


#### 문제2. 두 개 뽑아서 더하기

**문제 설명:**
정수 배열 numbers가 주어집니다. numbers에서 서로 다른 인덱스에 있는 두 개의 수를 뽑아 더해서 만들 수 있는 모든 수를 배열에 오름차순으로 담아 반환해주세요.

**제한 사항:**
- numbers의 길이는 2 이상 100 이하입니다.
- numbers의 모든 수는 0 이상 100 이하인 정수입니다.
- 반드시 스프레드 문법을 사용할 것

**입출력 예시:**
```plaintext
numbers	    result
[2,1,3,4,1]	[2,3,4,5,6,7]
[5,0,2,7]	[2,5,7,9,12]
```

**Solution:**
<details>
<summary>정답 보기</summary>
<div>

```javascript
function solution(numbers) {
    const result = new Set();
    for (let i = 0; i < numbers.length; i++) {
        for (let j = i + 1; j < numbers.length; j++) {
            result.add(numbers[i] + numbers[j]);
        }
    }
    return [...result].sort((a, b) => a - b);
}

// 테스트
console.log(solution([2, 1, 3, 4, 1])); // 출력: [2, 3, 4, 5, 6, 7]
console.log(solution([5, 0, 2, 7]));    // 출력: [2, 5, 7, 9, 12]
```

</div>
</details>
