### ISSUE TITLE
04.09.2023 32장, 41장, 42장

### ISSUE THREAD

**Issue by ooheunda** [ooheunda/js-deep-dive#15]
15회차 퀴즈 담당
기돈, 다은, 세민

```
<details>
<summary>정답 보기</summary>
<div>

여기에 정답을 써주세요

</div>
</details>
```

**Comment by ooheunda** [comment]
***개날먹 죄송합니다...***

1. 만약 ***이 비어 있고 ^^^^에 대기 중인 함수가 있다면 이벤트 루프는 순차적으로 ^^^^에 대기 중인 함수를 ***으로 이동시킨다.

<details>
<summary>정답 보기</summary>
<div>

***: 콜 스택
^^^^: 태스크 큐

</div>
</details>

<hr>

2. [프로그래머스 문제 풀러가기 (개쉬움)](https://school.programmers.co.kr/learn/courses/30/lessons/181906)

<details>
<summary>정답 보기</summary>
<div>

```javascript
function solution(my_string, is_prefix) {
    return +(my_string.startsWith(is_prefix));
}
```

</div>
</details>

<hr>

**Comment by lyukidon** [comment]
- 비동기 처리
    1. 콜 스택
    2. 힙
    3. 테스트 큐
    4. 이벤트 루프
    
    ---
    
    1. 객체를 저장하는 곳
    2. 비동기 함수가 저장되는 곳
    3. 실행 컨텍스트가 추가되고 제거되는 곳
    4. ~~테스크 큐~~에 대기 중인 함수를 ~~콜 스택~~으로 이동시킨다.
        <details>
        <summary>정답 보기</summary>
        <div>
        1 - c
        2 - a
        3 - b
        4 - d
        </div>
        </details>
        
- 호출
    - debounce 뜻
    - throttle 뜻
    <details>
    <summary>정답 보기</summary>
    <div>
    
    - 정답
        - debounce : 이벤트 생성 후 특정 시간이 지나면 이벤트가 1번만 발생하도록 함
        - throttle : 이벤트가 연속으로 발생해도, 특정 시간 때마다 이벤트가 발생하도록 함
        <details>
        <summary>사용되는 곳</summary>
        <div>
              - debounce : 자동 완성 ui 구현, 버튼 중복 클릭 방지 처리
              - throttle : scroll event나 무한스크롤 ui 구현
        </div>
        </details>

    </div>
    </details>

**Comment by lyukidon** [comment]
문제1. 호출
- debounce 뜻
- throttle 뜻

<details>
<summary>정답 보기</summary>
<div>
- 정답
    - debounce : 이벤트 생성 후 특정 시간이 지나면 이벤트가 1번만 발생하도록 함
    - throttle : 이벤트가 연속으로 발생해도, 특정 시간 때마다 이벤트가 발생하도록 함
- 사용되는 곳
    - debounce : 자동 완성 ui 구현, 버튼 중복 클릭 방지 처리
    - throttle : scroll event나 무한스크롤 ui 구현
</div>
</details>

---

문제2. HTTP 1과 2의 차이점

<details>
<summary>정답 보기</summary>
<div>

- 멀티 플렉싱 : 데이터 요청을 동시에 처리
- 서버 푸쉬 : 클라이언트가 요청하기 전에, 필요한 리소스를 전송
- 헤더 압축 : HPACK이라는 고급 압축 방법을 사용해, v1보다 더 작은 크기의 헤더를 전송

</div>
</details>

---

문제3. HTML, CSS, JavaScript를 파싱하고 나서 생성되는 트리 구조(parse tree)의 이름

<details>
<summary>정답 보기</summary>
<div>

- HTML -> DOM(Document Object Model)
- CSS -> CSSOM(CSS Object Model)
- JavaScript -> AST(Abstract Syntex Tree) → 바이트 코드를 생성해서 실행

</div>
</details>

---

문제4. `<script>` 태그는 body태그 내에 하단에 위치시키는 것이 올바르다. 그 이유는?

<details>
<summary>정답 보기</summary>
<div>

브라우저는 코드를 동기적으로 실행시킨다.
        
script 태그가 위치한 곳에 따라, DOM 생성이 지연된다.

- 문제점
    - script가 DOM을 조작하는 경우, DOM이 생성되지 않는 경우에는 오류 발생
    - DOM이 생성되기 전에 script를 실행하므로, 페이지 로딩이 오래걸린다.

</div>
</details>

---

문제5. HTML 노드 자료 구조의 형태는?

<details>
<summary>힌트</summary>
<div>

1. 트리 자료 구조
2. 그래프 자료 구조
3. 선형 자료 구조
4. 혼합 자료 구조
5. 스택 자료 구조

</div>
</details>

<details>
<summary>정답 보기</summary>
<div>

1. 트리 자료 구조

</div>
</details>

---

- CSS 선택자
    - 선택자와 맞는 태그를 고르시오
        
        ```html
        <html>
        	<input type="text" /> --- 1)
        	<input type="password" /> --- 2)
        	<input type="button" /> --- 3)
        	
        	<div>
        		<p>과일</p> --- 4)
        		<p>과일</p> --- 4)
        		<ul> --- 5)
        			<li>사과</li>
        			<li>딸기</li>
        		</ul>
        		<ul> --- 6)
        			<li>사과</li>
        			<li>딸기</li>
        		</ul>
        		<div>
        			<p>안녕하세요</p> --- 7)
        		</div>
        	</div>
        </html>
        ```
        
        1. input[type=text] {} 1
        
        ```html
        div p {
        	width: 100px;
        } 4,7
        ```
        
        1. div > p {} 4
        2. p + ul 5
        3. p ~ ul 5,6
<details>
<summary>정답 보기</summary>
<div>

1번 - 1)
2번 - 4, 7
3번 - 4
4번 - 5
5번 - 5, 6

</div>
</details>
