### ISSUE TITLE
05.12.2024 39장 (2)

### ISSUE THREAD

**Issue by ooheunda** [ooheunda/js-deep-dive#19]
19회차 퀴즈 담당
재연, 하온

```
<details>
<summary>정답 보기</summary>
<div>

여기에 정답을 써주세요

</div>
</details>
```

**Comment by HA0N1** [comment]
1번 innerHTML은 DOM 조작 방법보다 빠르고 간단하지만 문제점은? 3가지 정도

<details>
<summary>정답 보기</summary>
<div>

1. XSS 취약
2. 기존 요소 제거하고 새로 추가 도미(HTML을 다시 파싱) => appendChild 사용
3. 삽입 위치 지정 X => insertAdjacentHTML사용

</div>
</details>

2번 XSS공격에 대응하기 위해선? 

1. 데이터를 sanitization(살균) 한다.
2. textContent 사용한다 (HTML이 아닌 TEXT로 읽음)
3. cookie에 ip 주소를 저장해서 사용자 인증
4. 템플릿 엔진을 사용한다 (handlebars, ejs, pug 등)
5. HttpOnly(javaScript에서 접근할 수 없도록 설정) 및 Secure(HTTPS)사용
6. HTML 특수문자(<,>,(,),',",)를 HTML Entity로 바꾸기

<details>
<summary>정답 보기</summary>
<div>

1. 데이터를 sanitization(살균) 한다.
2. textContent 사용한다 (HTML이 아닌 TEXT로 읽음)
3. X
4. 템플릿 엔진을 사용한다 (handlebars, ejs, pug 등)
5. HttpOnly(javaScript에서 접근할 수 없도록 설정) 및 Secure(HTTPS)사용
6. HTML 특수문자(<,>,(,),',",)를 HTML Entity로 바꾸기

</div>
</details>

3번 DOM에 여러 요소를 효율적으로 (리페인트, 리플로우 최소화) 추가하려면 뭘 써야할까여

1. insertAdjacentHTML
2. textContent 
3. innerHTML
4. DocumentFragment 

<details>
<summary>정답 보기</summary>
<div>

4. DocumentFragment 

</div>
</details>
